version: '3.8'

services:
  postgres:
    image: docker.io/tensorchord/vchord-postgres:pg17-v0.3.0
    container_name: postgres_with_pgvectorscale # Updated container name
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-vectordb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
